title       = "ncbiassembly"
baseURL     = "https://ncbiassembly-cli.tamnd.com/"
description = "A command line for ncbiassembly."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/ncbiassembly-cli"
